### PR TITLE
Update CODEOWNERS to include brandonpollack23

### PR DESCRIPTION
**Pull request by hikalium**
Include @brandonpollack23 as a code owner of lium 🙌

### CODE REVIEW

**Comment by brandonpollack23** [comment]
!

You sure we align enough yet?

There's no rush

**Comment by hikalium** [comment]
Given that you contributed to lium so actively (e.g. creating internal documents, hosting an intern to work on lium, code reviews etc...), I think having you as a code owner will make lium better (of course, sometimes we have conflicts, but discussion is a good thing, so I'm confident that we are aligned now 😉 ) Thanks for all the contributions so far!

... of course, I want to hear the other maintainer's opinion as well (and this pull request will not be merged until another one agrees, so I think it should be safe enough)

So existing maintainers, please don't hesitate to raise your opinion ( regardless you agree / disagree with this proposal!)

**Comment by HidenoriKobayashi** [comment]
+1

**Review by mhiramat — APPROVED** [review]
LGTM!

**Pull request merged**
