### PR TITLE
treewide: Rename lium to cro3

### PR DESCRIPTION
**Pull request by mhiramat**
Rename `lium` to `cro3` according to our decision.

### CODE REVIEW

**Comment by hikalium** [comment]
It looks like running `cargo fmt` is needed . Please refer to the CI log and  fix that!

**Comment by mhiramat** [comment]
Ok, btw, `cargo fmt` shows below warnings. (Just FYI)
```
Warning: the `fn_args_layout` option is deprecated. Use `fn_params_layout`. instead
```

**Comment by hikalium** [comment]
Makefile also contains "lium" keyword still...
```
 21     @printf "\nlium is successfully installed at `which cro3`. Try \`cro3 --help\` if you want!\n"
```
Did you only replaced the name in *.rs files?

**Comment by hikalium** [comment]
Sorry, it looks like that's the only line missing. All other usage seems to be fixed. Thank you! (Please feel free to submit after fixing the Makefile!)

**Review by hikalium — APPROVED** [review]
Other than Makefile, looks good to me (Thanks for coming up with a beautiful new name!!! (I really liked it ;) ))

**Comment by mhiramat** [comment]
OK, let me update it and merge.

**Pull request merged**
